### ISSUE TITLE
Avoid global build system

### ISSUE THREAD

**Issue by kLabz** [saint11/MoonLove-Faststart#1]
Not an issue, rather some kind of suggestion if you find it appropriate.

You can avoid adding a global build system, and create a project-specific build system inside your `myproject.sublime-project` file. Assuming it is at the root of your project directory, something like that would achieve the same thing as your global build system (without requiring to select the build system, it will be selected automatically when opening the project):

```json
{
	"build_systems": [
		{
			"shell_cmd": "moonc -t lua/. src/. && love lua/.",
			"file_regex": "^\\s*(.+):(\\d+): (?:lines \\d+-\\d+|character(?:s \\d+-| )(\\d+)) : (.*)$",
			"name": "Compile my project",
			"working_dir": "${project_path:${folder:${file_path}}}"
		}
	],
	"folders": [
		{
			"name": "My Project Name",
			"path": ".",
			"folder_exclude_patterns": [
				".git"
			],
			"file_exclude_patterns": [
				"*.sublime-*"
			]
		}
	]
}
```

The `file_regex` can be removed. I added it because that's the one I use for haxe (so it's not correct for your use case) to parse the build result and make links out of errors so that I can click on one and go to the corresponding file/line. Maybe you could adjust it to your build command (if not, just drop this line).

I added some other examples of project configuration, like renaming folders and excluding files/directories in your "folders" view.

**Comment by saint11** [comment]
Oh this is great! I will fix that 😁

**Comment by saint11** [comment]
Fixed it! Thanks a lot for the help :D
